Script started on Thu 07 Oct 2021 07:47:38 PM EDT
tuser@tutor-vserver:~/hw1_part2$ ls
typescript
tuser@tutor-vserver:~/hw1_part2$ scp zmumbcs@users.cs.umb.edu:/home/zmumb cs/cs444/hw1_part2/testio.lnx .
zmumbcs@users.cs.umb.edu's password: 
testio.lnx                               0%    0     0.0KB/s   --:-- ETAtestio.lnx                             100%   47KB  47.4KB/s   00:00    
tuser@tutor-vserver:~/hw1_part2$ ls
[0m[01;32mtestio.lnx[0m  typescript
tuser@tutor-vserver:~/hw1_part2$ mtip -f testio.lnx
For command help, type ~?
For help on args, rerun without args
Code starts at 0x100100
Using board # 1 
Please type <CR> to confirm console setting: 
Setting console dev to COM2Console: colour EGA+ 80x25
COM1 at 0x03f8 (irq = 4) is a 16550A
COM2 at 0x02f8 (irq = 3) is a 16550A

                 Welcome to UMB Tutor for the PC
   UMB Tutor is a 32-bit protected-mode PC debugger/downloader,
       based on Linux, UMB Tutor for m68k, and remote gdb.
UMB Tutor is free software and you are welcome to distribute copies
of it under certain conditions.  There is no warranty for this program.
The copyright and warranty provisions follow the Gnu general public
license, available for view in gdb and elsewhere.  Full sources available.
--bugs, suggestions, questions to eoneil@cs.umb.edu

Exception 3 at EIP=00057a9b: Breakpoint
Tutor> ~downloading testio.lnx

............Done.

Download done, setting EIP to 100100.
Tutor> go 100100
Running with device TTY1

Trying simple write(4 chars)...
hi!
write of 4 returned 4
<doing delay>
Trying longer write (9 chars)
abcdefghiwrite of 9 returned 9
<doing delay>

Trying write of 80-char string...
AABBCCDDEEFFGGHHIIJJKKLLMMNNOOPPQQRRSSTTUUVVWWXXYYZZ[[\\]]^^__``aabbccddeeffgghh
write returned 80
<doing delay>

Type 10 chars input to test typeahead while looping for delay...
<doing delay>
1234567890
Got 10 chars into buf. Trying write of buf...
1234567890
Trying another 10 chars read right away...
0987654321
Got 10 chars on second read
0987654321

Now turning echo off--

Type 20 chars input, note lack of echoes...
<doing delay>

Trying write of buf...
abcdefg1234567hzmhzm
Asked for 20 characters; got 20
Exception 3 at EIP=00100110: Breakpoint
Tutor> md 300000
00300000    3c 68 3c 69 3c 21 3c 0a 2a 2a 2a 2a 2a 3c 61 3c <h<i<!<.*****<a<
Tutor> 
00300010    62 3c 63 3c 64 3c 65 3c 66 2a 2a 2a 2a 2a 2a 2a b<c<d<e<f*******
Tutor> 
00300020    3c 67 2a 2a 3c 68 2a 2a 3c 69 2a 2a 3c 41 3c 41 <g**<h**<i**<A<A
Tutor> 
00300030    3c 42 3c 42 3c 43 3c 43 2a 2a 2a 2a 2a 2a 2a 3c <B<B<C<C*******<
Tutor> 
00300040    44 2a 2a 3c 44 2a 2a 3c 45 2a 2a 3c 45 2a 2a 3c D**<D**<E**<E**<
Tutor> ~q 
Quit handler: 
killing process 2140 Leaving board #1
tuser@tutor-vserver:~/hw1_part2$ exit
exit

Script done on Thu 07 Oct 2021 07:49:41 PM EDT
