Script started on Sun 07 Nov 2021 09:47:41 PM EST
tuser@tutor-vserver:~/homework/hw2$ ls
typescript
tuser@tutor-vserver:~/homework/hw2$ scp zmumbcs@users.cs.umb.edu:/home/zmuumbcs/cs444/hw2/test1.lnx .
zmumbcs@users.cs.umb.edu's password: 
test1.lnx                                0%    0     0.0KB/s   --:-- ETAtest1.lnx                              100%   51KB  50.7KB/s   00:00    
tuser@tutor-vserver:~/homework/hw2$ ls
[0m[01;32mtest1.lnx[0m  typescript
tuser@tutor-vserver:~/homework/hw2$ mtip -f test1.lnx
For command help, type ~?
For help on args, rerun without args
Code starts at 0x100100
Using board # 1 
Please type <CR> to confirm console setting: 
Setting console dev to COM2Console: colour EGA+ 80x25
COM1 at 0x03f8 (irq = 4) is a 16550A
COM2 at 0x02f8 (irq = 3) is a 16550A

                 Welcome to UMB Tutor for the PC
   UMB Tutor is a 32-bit protected-mode PC debugger/downloader,
       based on Linux, UMB Tutor for m68k, and remote gdb.
UMB Tutor is free software and you are welcome to distribute copies
of it under certain conditions.  There is no warranty for this program.
The copyright and warranty provisions follow the Gnu general public
license, available for view in gdb and elsewhere.  Full sources available.
--bugs, suggestions, questions to eoneil@cs.umb.edu

Exception 3 at EIP=00057a9b: Breakpoint
Tutor> ~downloading test1.lnx

............Done.

Download done, setting EIP to 100100.
Tutor> go 100100
running with device TTY1

trying simple write (4 chars) ...
calling SYSWRITE
hi!
write of 4 returned 4
<doing delay>

trying longer write (9 chars) ...
calling SYSWRITE
abcdefghiwrite of 9 returned 9
<doing delay>

trying write of 80-char string...
calling SYSWRITE
AABBCCDDEEFFGGHHIIJJKKLLMMNNOOPPQQRRSSTTUUVVWWXXYYZZ[[\\]]^^__``aabbccddeeffgghh
write returned 80
<doing delay>
echo control syscall is not available
echo is off

Type 10 chars input to test typeahead while looping for delay...
<doing delay>
calling SYSREAD

Got 10 chars into buf. Trying write of buf...
calling SYSWRITE
ab12cd34ef
Trying another 10 chars read right away...
calling SYSREAD

Got 10 chars on second read
calling SYSWRITE
56gh78ij90
Type 20 chars input, note lack of echoes...
<doing delay>
calling SYSREAD

Trying write of buf...
calling SYSWRITE
abcdefghi1234567890a
Asked for 20 characters; got 20

end of test
calling SYSEXIT

exit code -> 0
shutting down
Exception 3 at EIP=00100110: Breakpoint
Tutor> md 1 300000
00300000    2a 3e 68 40 32 2a 3e 69 40 32 2a 3e 21 40 32 2a *>h@2*>i@2*>!@2*
Tutor> md 3    
00300010    3e 0a 40 32 2a 2a 3e 61 40 32 2a 3e 62 40 32 2a >.@2**>a@2*>b@2*
Tutor> 
00300020    3e 63 40 32 2a 3e 64 40 32 2a 3e 65 40 32 2a 3e >c@2*>d@2*>e@2*>
Tutor> 
00300030    66 40 32 2a 2a 3e 67 40 32 2a 2a 3e 68 40 32 2a f@2**>g@2**>h@2*
Tutor> 
00300040    2a 3e 69 40 32 2a 2a 3e 41 40 32 2a 3e 41 40 32 *>i@2**>A@2*>A@2
Tutor> ~q 
Quit handler: 
killing process 2369 Leaving board #1
tuser@tutor-vserver:~/homework/hw2$ exit
exit

Script done on Sun 07 Nov 2021 09:51:26 PM EST
