Script started on Mon 13 Dec 2021 11:50:16 PM EST
tuser@tutor-vserver:~/homework/hw3$ scp zmumbcs@users.cs.umb.edu:/home/zm umbcs/cs444/homework/hw3 .[K[K/tunix.lnx .
zmumbcs@users.cs.umb.edu's password: 
tunix.lnx                                0%    0     0.0KB/s   --:-- ETAtunix.lnx                              100%   62KB  62.4KB/s   00:01    
tuser@tutor-vserver:~/homework/hw3$ ls
[0m[01;32mtunix.lnx[0m  typescript
tuser@tutor-vserver:~/homework/hw3$ mtip -f tunix.lnx
For command help, type ~?
For help on args, rerun without args
Code starts at 0x100100
Using board # 1 
Please type <CR> to confirm console setting: 
Setting console dev to COM2Console: colour EGA+ 80x25
COM1 at 0x03f8 (irq = 4) is a 16550A
COM2 at 0x02f8 (irq = 3) is a 16550A

                 Welcome to UMB Tutor for the PC
   UMB Tutor is a 32-bit protected-mode PC debugger/downloader,
       based on Linux, UMB Tutor for m68k, and remote gdb.
UMB Tutor is free software and you are welcome to distribute copies
of it under certain conditions.  There is no warranty for this program.
The copyright and warranty provisions follow the Gnu general public
license, available for view in gdb and elsewhere.  Full sources available.
--bugs, suggestions, questions to eoneil@cs.umb.edu

Exception 3 at EIP=00057a9b: Breakpoint
Tutor> ~downloading tunix.lnx

..............Done.

Download done, setting EIP to 100100.
Tutor> go 100100
aaaaaaaaaazzzAAAAAAAAAA
 EXIT CODE IS 2
bbbbbbbbbb
 EXIT CODE IS 4
cccccccccc
 EXIT CODE IS 6

SHUTTING THE SYSTEM DOWN!
Debug log from run:
Marking kernel events as follows:
  ^a   COM2 input interrupt, a received
  ~    COM2 output interrupt, ordinary char output
  ~e   COM2 output interrupt, echo output
  ~s   COM2 output interrupt, shutdown TX ints
|(0 -1)~~~~~~~~s~~~s~~~s~~~s~~~s~~~~~s~~~~~~~~s~~~s~~~s~~~s~~~s|(1Z-2)~~~~~~~~s~~~s~~~s~~~s~~~s|(2Z-3)~~~~~~~~s~~~s~~~s~~~s~~~s
LEAVE KERNEL!

Exception 3 at EIP=0010010b: Breakpoint
Tutor> mdd 300000
00300000    2030287c 7e29312d 7e7e7e7e 737e7e7e |(0 -1)~~~~~~~~s
Tutor> 
00300010    737e7e7e 737e7e7e 737e7e7e 737e7e7e ~~~s~~~s~~~s~~~s
Tutor> 
00300020    7e7e7e7e 7e7e737e 7e7e7e7e 7e737e7e ~~~~~s~~~~~~~~s~
Tutor> 
00300030    7e737e7e 7e737e7e 7e737e7e 7c737e7e ~~s~~~s~~~s~~~s|
Tutor> 
00300040    2d5a3128 7e7e2932 7e7e7e7e 7e737e7e (1Z-2)~~~~~~~~s~
Tutor> 
00300050    7e737e7e 7e737e7e 7e737e7e 7c737e7e ~~s~~~s~~~s~~~s|
Tutor> 
00300060    2d5a3228 7e7e2933 7e7e7e7e 7e737e7e (2Z-3)~~~~~~~~s~
Tutor> 
00300070    7e737e7e 7e737e7e 7e737e7e 00737e7e ~~s~~~s~~~s~~~s.
Tutor> 
00300080    00000000 00000000 00000000 00000000 ................
Tutor> ~q 
Quit handler: 
killing process 2044 Leaving board #1
tuser@tutor-vserver:~/homework/hw3$ 
tuser@tutor-vserver:~/homework/hw3$ exit
exit

Script done on Mon 13 Dec 2021 11:52:04 PM EST
